name: Add Permissions Block

on:
  workflow_dispatch:

jobs:
  generate-file-list:
    runs-on: ubuntu-latest
    outputs:
      file-list: ${{ steps.set-output.outputs.file-list }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GK_PAT }}

      - name: Set Output
        id: set-output
        run: |
          file_list=$(find .github/workflows -type f -name "*.yml" -not -name 'token-permission.yml' -printf '\"%p\",' | sed 's/,$//')
          file_list="[$file_list]"
          echo "File List: $file_list"
          echo "::set-output name=file-list::$file_list"        
                      
  add-permissions-block:
    runs-on: ubuntu-latest
    needs: generate-file-list
    strategy:
      matrix:
        file: ${{ fromJson(needs.generate-file-list.outputs.file-list) }}
        #files: ${{ needs.set_files.outputs.files }}
        #file: [".github/workflows/github-rest-api1.yml",".github/workflows/github-rest-api2.yml"]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GK_PAT }}

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruamel.yaml

    - name: Add Permissions Block
      id: add_permissions
      run: |
        python script/check_permissions.py "${{ matrix.file }}"

    - name: Check for Permissions
      id: check_permissions
      run: |
          echo "Permissions found: ${{ steps.add_permissions.outputs.permissions_found }}"

    - name: Take Action based on Permissions
      run: |
          if [ "${{ steps.add_permissions.outputs.permissions_found }}" == "false" ]; then
            echo "Permissions block not found. Adding permissions block..."
            echo "File path: ${{ matrix.file }}"
            sed -i -e '/^jobs:/i \permissions: write-all\n' ${{ matrix.file }}
          else
            echo "Permissions block found. Continuing..."
          fi
      shell: bash

    - name: Check for Changes
      id: check_changes
      run: |
        if git diff --quiet; then
        echo "No changes to commit. Skipping commit step."
        echo "::set-output name=changes::false"
        else
        echo "::set-output name=changes::true"
        fi
      shell: bash

    - name: Commit Changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
        git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
        git add .
        git commit -m "Added Permission Block- $(date +"%Y-%m-%d %H:%M:%S")"
        git push # Replace 'branch-name' with the branch name
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GITHUB_TOKEN: ${{ secrets.GK_PAT }}


